// #115: the first writable PATH dir was an rvm gemset, so the shim vanished on
// `rvm use` and a dead copy further down PATH took over unseen.

import * as path from "node:path";
import { parseShimTargets } from "./cli-shim";

/** Dirs a version manager swaps or regenerates per version (`rbenv rehash`
 *  wipes its shims), so a shim there drops off PATH on the next switch. */
const VERSION_MANAGED = [
  "/.rvm/",
  "/.rbenv/",
  "/.pyenv/",
  "/.nvm/",
  "/.asdf/",
  "/.fnm/",
  "/.gem/",
  "/mise/installs/",
  "/node_modules/.bin",
];

const normalizeDir = (dir: string) => path.normalize(dir).replace(/\/+$/, "");

export function isVersionManagedDir(dir: string): boolean {
  const normalized = `${normalizeDir(dir)}/`;
  return VERSION_MANAGED.some((marker) => normalized.includes(marker));
}

export interface InstallDirChoice {
  dir: string;
  onPath: boolean;
}

/** ~/.local/bin when PATH has it; else the first writable PATH dir no version
 *  manager owns; else ~/.local/bin flagged off-PATH. */
export function chooseCliInstallDir(
  pathEntries: string[],
  home: string,
  isWritableDir: (dir: string) => boolean,
): InstallDirChoice {
  const preferred = path.join(home, ".local", "bin");
  if (pathEntries.some((entry) => normalizeDir(entry) === preferred)) {
    return { dir: preferred, onPath: true };
  }
  const stable = pathEntries.find(
    (entry) => !isVersionManagedDir(entry) && isWritableDir(entry),
  );
  if (stable) return { dir: stable, onPath: true };
  return { dir: preferred, onPath: false };
}

export interface AyaCopy {
  path: string;
  /** Generated by Aya (current or legacy shim), so safe to rewrite or remove. */
  ours: boolean;
  /** Ours, and none of its targets is executable any more. */
  broken: boolean;
}

/** The legacy `exec "<path>" "$@"` shim has no marker, so it only counts as
 *  ours when it execs an `aya` - a foreign wrapper stays foreign. */
export function ayaShimTargets(content: string): string[] {
  const targets = parseShimTargets(content);
  return targets.every((target) => path.basename(target) === "aya")
    ? targets
    : [];
}

/** The OS cannot exec inside .asar (#39: "Not a directory"), but Electron's
 *  patched fs reads into archives, so an X_OK probe from the app passes. */
export function insideAsarArchive(target: string): boolean {
  return path
    .normalize(target)
    .split(path.sep)
    .slice(0, -1)
    .some((segment) => segment.endsWith(".asar"));
}

export interface CliInstallPlan {
  rewrite: string[];
  remove: string[];
}

/** Our other copies: removed from version-managed dirs (they only shadow the
 *  stable install), rewritten elsewhere. Foreign scripts are never touched. */
export function planCliInstall(copies: AyaCopy[], target: string): CliInstallPlan {
  const plan: CliInstallPlan = { rewrite: [], remove: [] };
  for (const copy of copies) {
    if (!copy.ours || copy.path === target) continue;
    if (isVersionManagedDir(path.dirname(copy.path))) plan.remove.push(copy.path);
    else plan.rewrite.push(copy.path);
  }
  return plan;
}

export const offPathNote = (choice: InstallDirChoice) =>
  choice.onPath ? "" : ` - ${choice.dir} is not on your PATH, add it to use the command`;

/** The Settings line for the `aya` command. `copies` is in PATH order, so the
 *  first one is what a shell runs; the rest are shadowed. */
export function describeCliStatus(
  copies: AyaCopy[],
  choice: InstallDirChoice,
): string | undefined {
  const active = copies[0];
  if (!active) return `Install to ${path.join(choice.dir, "aya")}${offPathNote(choice)}`;

  const notes: string[] = [];
  if (active.broken) {
    notes.push("it points at a moved or renamed Aya.app");
  } else if (active.ours && isVersionManagedDir(path.dirname(active.path))) {
    notes.push(
      "that directory belongs to a version manager and drops off PATH when you switch versions",
    );
  } else if (!active.ours) {
    return `${active.path} comes first on PATH and was not installed by Aya.`;
  }
  const staleBelow = copies.slice(1).filter((copy) => copy.broken);
  if (staleBelow.length > 0) {
    notes.push(
      `a dead copy further down PATH takes over if it disappears (${staleBelow
        .map((copy) => copy.path)
        .join(", ")})`,
    );
  }
  if (notes.length === 0) return undefined;
  return `Installed at ${active.path}, but ${notes.join("; and ")} - click Reinstall to repair.`;
}
