// Where the `aya` shim goes, and what every `aya` already on PATH is (#115).
// The installer used to take the FIRST writable PATH entry, which on a machine
// with rvm/rbenv/nvm/asdf is a version-pinned dir: the shim vanished on the
// next `rvm use`, and a dead pre-#39 shim further down PATH took over, unseen
// because status only ever looked at the first hit. Pure: main.ts does the IO.

import * as path from "node:path";
import { parseShimTargets } from "./cli-shim";

/** Dirs a version manager prepends and swaps per version (or regenerates:
 *  `rbenv rehash` wipes its shims dir). A shim there drops off PATH on the next
 *  version switch, so it is never an install target. */
const VERSION_MANAGED = [
  "/.rvm/",
  "/.rbenv/",
  "/.pyenv/",
  "/.nvm/",
  "/.asdf/",
  "/.fnm/",
  "/.gem/",
  "/mise/installs/",
  "/node_modules/.bin",
];

export function isVersionManagedDir(dir: string): boolean {
  const normalized = `${path.normalize(dir).replace(/\/+$/, "")}/`;
  return VERSION_MANAGED.some((marker) => normalized.includes(marker));
}

const sameDir = (a: string, b: string) =>
  path.normalize(a).replace(/\/+$/, "") === path.normalize(b).replace(/\/+$/, "");

export interface InstallDirChoice {
  dir: string;
  onPath: boolean;
}

/** ~/.local/bin when PATH has it (created on install if missing); else the
 *  first writable PATH dir a version manager does not own; else ~/.local/bin
 *  anyway, flagged off-PATH so the status can say so. */
export function chooseCliInstallDir(
  pathEntries: string[],
  home: string,
  isWritableDir: (dir: string) => boolean,
): InstallDirChoice {
  const preferred = path.join(home, ".local", "bin");
  if (pathEntries.some((entry) => sameDir(entry, preferred))) {
    return { dir: preferred, onPath: true };
  }
  const stable = pathEntries.find(
    (entry) => !isVersionManagedDir(entry) && isWritableDir(entry),
  );
  if (stable) return { dir: stable, onPath: true };
  return { dir: preferred, onPath: false };
}

export interface AyaCopy {
  path: string;
  /** Generated by Aya (current or legacy shim), so safe to rewrite or remove. */
  ours: boolean;
  /** Ours, and none of its targets is executable any more. */
  broken: boolean;
}

/** Targets of an Aya-generated shim; [] for anything else. The legacy
 *  one-line `exec "<path>" "$@"` form carries no marker, so it only counts
 *  when it execs an `aya` - a foreign wrapper stays foreign. */
export function ayaShimTargets(content: string): string[] {
  const targets = parseShimTargets(content);
  return targets.every((target) => path.basename(target) === "aya")
    ? targets
    : [];
}

/** True for a path INSIDE an .asar archive. The OS cannot exec those (the #39
 *  shim died with "Not a directory"), but Electron's patched fs reads into
 *  archives, so an X_OK probe from the app says they are fine. */
export function insideAsarArchive(target: string): boolean {
  return path
    .normalize(target)
    .split(path.sep)
    .slice(0, -1)
    .some((segment) => segment.endsWith(".asar"));
}

export interface CliInstallPlan {
  /** Our copies to rewrite in place with a fresh shim. */
  rewrite: string[];
  /** Our copies to delete: they live in a version-managed dir. */
  remove: string[];
}

/** What Reinstall does to the copies already on PATH besides writing
 *  `target`. Foreign scripts are never touched. */
export function planCliInstall(copies: AyaCopy[], target: string): CliInstallPlan {
  const plan: CliInstallPlan = { rewrite: [], remove: [] };
  for (const copy of copies) {
    if (!copy.ours || copy.path === target) continue;
    if (isVersionManagedDir(path.dirname(copy.path))) plan.remove.push(copy.path);
    else plan.rewrite.push(copy.path);
  }
  return plan;
}

/** The Settings line for the `aya` command. `copies` is in PATH order, so the
 *  first one is what a shell runs; the rest are shadowed. */
export function describeCliStatus(
  copies: AyaCopy[],
  choice: InstallDirChoice,
): string | undefined {
  const target = path.join(choice.dir, "aya");
  const offPath = choice.onPath
    ? ""
    : ` - ${choice.dir} is not on your PATH, add it to use the command`;
  const active = copies[0];
  if (!active) return `Install to ${target}${offPath}`;

  const notes: string[] = [];
  if (active.broken) {
    notes.push("it points at a moved or renamed Aya.app");
  } else if (active.ours && isVersionManagedDir(path.dirname(active.path))) {
    notes.push(
      "that directory belongs to a version manager and drops off PATH when you switch versions",
    );
  } else if (!active.ours) {
    return `${active.path} comes first on PATH and was not installed by Aya.`;
  }
  const staleBelow = copies.slice(1).filter((copy) => copy.broken);
  if (staleBelow.length > 0) {
    notes.push(
      `a dead copy further down PATH takes over if it disappears (${staleBelow
        .map((copy) => copy.path)
        .join(", ")})`,
    );
  }
  if (notes.length === 0) return undefined;
  return `Installed at ${active.path}, but ${notes.join("; and ")} - click Reinstall to repair.`;
}
