// The installed `aya` command is a tiny shim that execs the CLI bundled
// inside the packaged app. The bundle path is baked at install time, so
// moving or renaming Aya.app used to kill the shim with sh's cryptic
// "No such file or directory" (follow-up on #42). The generated script now
// self-heals via the default install location and otherwise points the user
// at the repair path; parseShimTargets lets cliStatus() detect a dead shim
// and surface "Reinstall" in Settings.

import * as path from "node:path";

// Marker baked into every shim we generate; parseShimTargets refuses to parse
// AYA_CLI lines from scripts that lack it, so foreign scripts that merely
// contain a similar-looking string are never misclassified as our shim.
const SHIM_MARKER = "Generated by Aya";

/** POSIX single-quote escaping: wrap in ' and turn embedded ' into '\''.
 *  Single quotes inhibit ALL shell expansion ($, backticks, !), which
 *  double-quoted JSON.stringify output does not - a path containing $HOME
 *  would be expanded at shim runtime and exec the wrong file. */
function shQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

/** POSIX-sh shim that prefers the baked CLI path, falls back to the default
 *  install location (when one exists and differs), and otherwise explains
 *  how to repair instead of failing cryptically. Paths are embedded
 *  single-quoted so no shell expansion can mangle them at runtime. */
export function renderCliShim(
  primary: string,
  fallback: string | null,
): string {
  const lines = [
    "#!/bin/sh",
    `# ${SHIM_MARKER} (Settings -> aya command-line tool).`,
    `AYA_CLI=${shQuote(primary)}`,
  ];
  if (fallback && fallback !== primary) {
    lines.push(
      `if [ ! -x "$AYA_CLI" ]; then AYA_CLI=${shQuote(fallback)}; fi`,
    );
  }
  lines.push(
    'if [ ! -x "$AYA_CLI" ]; then',
    '  echo "aya: cannot find Aya.app (moved or renamed?). Open Aya -> Settings -> aya command-line tool -> Reinstall." >&2',
    "  exit 127",
    "fi",
    'exec "$AYA_CLI" "$@"',
    "",
  );
  return lines.join("\n");
}

/** Candidate CLI paths a previously-installed shim points at, in order.
 *  Understands the current single-quoted AYA_CLI=... form (only when the
 *  shim carries our marker comment, so foreign scripts that merely contain a
 *  lookalike string parse to []) and the legacy single-line
 *  `exec "<path>" "$@"` form from the first #42 fix. */
export function parseShimTargets(content: string): string[] {
  const targets: string[] = [];
  if (content.includes(SHIM_MARKER)) {
    for (const match of content.matchAll(
      /AYA_CLI='((?:[^']|'\\'')*)'(?:;|$)/gm,
    )) {
      targets.push(match[1].replaceAll(`'\\''`, "'"));
    }
  }
  if (targets.length === 0) {
    const legacy = content.match(/^exec ("(?:[^"\\]|\\.)*") "\$@"$/m);
    if (legacy) {
      try {
        targets.push(JSON.parse(legacy[1]) as string);
      } catch {
        // not ours
      }
    }
  }
  return targets;
}

/** Where the CLI lives when Aya sits in the default install location - the
 *  shim's self-heal target after the app was moved back / renamed / updated.
 *  Only macOS has a stable well-known location; elsewhere there is none. */
export function defaultInstallAyaCliPath(
  platform: NodeJS.Platform,
): string | null {
  if (platform !== "darwin") return null;
  return path.join(
    "/Applications",
    "Aya.app",
    "Contents",
    "Resources",
    "app.asar.unpacked",
    "bin",
    "aya",
  );
}
