// #115: with an rvm gemset first on PATH, Settings must not call the CLI
// healthy while a dead shim waits below it, and Reinstall must leave one
// working shim in ~/.local/bin - checked on disk, not just in the message.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { test, expect } from "./fixtures";
import { fireShortcut } from "./helpers/shortcut";

test.use({ seedOptions: { cliInstallHarness: true } });

test("Reinstall moves the shim out of the rvm gemset and repairs the dead copy", async ({
  window,
  app,
  seeded,
}) => {
  const home = join(seeded.root, "cli-home");
  const gemsetShim = join(home, ".rvm", "gems", "ruby-3.4.4", "bin", "aya");
  const localShim = join(home, ".local", "bin", "aya");
  const repoCli = join(__dirname, "..", "bin", "aya");

  await fireShortcut(app, "open-settings");
  const settings = window.locator(".aya-modal--settings");
  await expect(settings).toBeVisible();
  const row = settings.locator(".aya-settings-general-row", {
    hasText: "aya command-line tool",
  });

  // Before: the first copy works, but it lives in a version manager's dir and
  // the one below it is dead - both must be named, not "Installed at ...".
  await expect(row).toContainText(gemsetShim);
  await expect(row).toContainText("version manager");
  await expect(row).toContainText(`dead copy further down PATH takes over if it disappears (${localShim})`);

  await row.getByRole("button", { name: "Reinstall" }).click();

  await expect(row).toContainText(`Installed at ${localShim}`);
  await expect(row).not.toContainText("Reinstall to repair");
  expect(existsSync(gemsetShim), "the gemset copy was left to shadow the stable one").toBe(false);
  const shim = readFileSync(localShim, "utf8");
  expect(shim).toContain("Generated by Aya");
  expect(shim).toContain(`AYA_CLI='${repoCli}'`);
  expect(shim).not.toContain("app.asar/bin/aya");
});
