// #115: Settings must not call the CLI healthy while a dead shim waits below an
// rvm gemset copy, and Reinstall must leave only working shims, checked on disk.

import { existsSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Page } from "@playwright/test";
import { test, expect } from "./fixtures";
import { fireShortcut } from "./helpers/shortcut";

function cliRow(window: Page) {
  return window
    .locator(".aya-modal--settings")
    .locator(".aya-settings-general-row", { hasText: "aya command-line tool" });
}

const gemsetShimIn = (home: string) => join(home, ".rvm", "gems", "ruby-3.4.4", "bin", "aya");

test.describe("rvm gemset first on PATH", () => {
  test.use({ seedOptions: { cliInstallHarness: true } });

  test("Reinstall moves the shim out of the rvm gemset and repairs the dead copies", async ({
    window,
    app,
    seeded,
  }) => {
    const home = join(seeded.root, "cli-home");
    const gemsetShim = gemsetShimIn(home);
    const homeShim = join(home, "bin", "aya");
    const localShim = join(home, ".local", "bin", "aya");
    const foreignAya = join(home, "tools", "aya");
    const foreignScript = readFileSync(foreignAya, "utf8");
    const repoCli = join(__dirname, "..", "bin", "aya");

    await fireShortcut(app, "open-settings");
    const row = cliRow(window);

    // Before: the first copy works but sits in a version manager's dir, and the
    // copies below it are dead - all must be named.
    await expect(row).toContainText(gemsetShim);
    await expect(row).toContainText("version manager");
    await expect(row).toContainText(
      `dead copy further down PATH takes over if it disappears (${homeShim}, ${localShim})`,
    );

    await row.getByRole("button", { name: "Reinstall" }).click();

    await expect(row).toContainText(`Installed at ${localShim}`);
    await expect(row).not.toContainText("Reinstall to repair");
    expect(existsSync(gemsetShim), "the gemset copy was left to shadow the stable one").toBe(false);
    expect(readFileSync(foreignAya, "utf8")).toBe(foreignScript);
    for (const shimPath of [localShim, homeShim]) {
      const shim = readFileSync(shimPath, "utf8");
      expect(shim).toContain("Generated by Aya");
      expect(shim).toContain(`AYA_CLI='${repoCli}'`);
      expect(shim).not.toContain("app.asar/bin/aya");
    }
  });

  test("Reinstall refuses to write through a foreign aya at the target", async ({
    window,
    app,
    seeded,
  }) => {
    const home = join(seeded.root, "cli-home");
    const localShim = join(home, ".local", "bin", "aya");
    const foreign = "#!/bin/sh\necho mine\n";
    writeFileSync(localShim, foreign);

    await fireShortcut(app, "open-settings");
    const row = cliRow(window);
    await row.getByRole("button", { name: "Reinstall" }).click();

    await expect(row).toContainText(`${localShim} exists and was not installed by Aya`);
    expect(readFileSync(localShim, "utf8")).toBe(foreign);
    expect(existsSync(gemsetShimIn(home))).toBe(true);
  });

  test("Reinstall refuses to write through a symlink at the target", async ({
    window,
    app,
    seeded,
  }) => {
    const home = join(seeded.root, "cli-home");
    const localShim = join(home, ".local", "bin", "aya");
    // Aya-shaped content behind the link, so only the symlink check can refuse.
    const linked = join(home, "bin", "aya");
    const linkedScript = readFileSync(linked, "utf8");
    rmSync(localShim);
    symlinkSync(linked, localShim);

    await fireShortcut(app, "open-settings");
    const row = cliRow(window);
    await row.getByRole("button", { name: "Reinstall" }).click();

    await expect(row).toContainText(`${localShim} exists and was not installed by Aya`);
    expect(readFileSync(linked, "utf8")).toBe(linkedScript);
  });

  test("~/.local/bin listed on PATH but missing is still the target", async ({
    window,
    app,
    seeded,
  }) => {
    const localBin = join(seeded.root, "cli-home", ".local", "bin");
    rmSync(localBin, { recursive: true });

    await fireShortcut(app, "open-settings");
    const row = cliRow(window);
    await row.getByRole("button", { name: "Reinstall" }).click();

    await expect(row).toContainText(`Installed at ${join(localBin, "aya")}`);
    expect(readFileSync(join(localBin, "aya"), "utf8")).toContain("Generated by Aya");
  });
});

test.describe("~/.local/bin off PATH", () => {
  test.use({ seedOptions: { cliInstallHarness: "off-path" } });

  test("Reinstall says the new shim is off PATH and keeps the only working copy", async ({
    window,
    app,
    seeded,
  }) => {
    const home = join(seeded.root, "cli-home");
    const localBin = join(home, ".local", "bin");

    await fireShortcut(app, "open-settings");
    const row = cliRow(window);
    await row.getByRole("button", { name: "Reinstall" }).click();

    await expect(row).toContainText(
      `Installed at ${join(localBin, "aya")} - ${localBin} is not on your PATH`,
    );
    expect(existsSync(gemsetShimIn(home))).toBe(true);
  });
});
