// #115: Settings must not call the CLI healthy while a dead shim waits below an
// rvm gemset copy, and Reinstall must leave only working shims, checked on disk.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { test, expect } from "./fixtures";
import { fireShortcut } from "./helpers/shortcut";

test.use({ seedOptions: { cliInstallHarness: true } });

test("Reinstall moves the shim out of the rvm gemset and repairs the dead copies", async ({
  window,
  app,
  seeded,
}) => {
  const home = join(seeded.root, "cli-home");
  const gemsetShim = join(home, ".rvm", "gems", "ruby-3.4.4", "bin", "aya");
  const homeShim = join(home, "bin", "aya");
  const localShim = join(home, ".local", "bin", "aya");
  const foreignAya = join(home, "tools", "aya");
  const foreignScript = readFileSync(foreignAya, "utf8");
  const repoCli = join(__dirname, "..", "bin", "aya");

  await fireShortcut(app, "open-settings");
  const settings = window.locator(".aya-modal--settings");
  await expect(settings).toBeVisible();
  const row = settings.locator(".aya-settings-general-row", {
    hasText: "aya command-line tool",
  });

  // Before: the first copy works but sits in a version manager's dir, and the
  // copies below it are dead - all must be named.
  await expect(row).toContainText(gemsetShim);
  await expect(row).toContainText("version manager");
  await expect(row).toContainText(`dead copy further down PATH takes over if it disappears (${homeShim}, ${localShim})`);

  await row.getByRole("button", { name: "Reinstall" }).click();

  await expect(row).toContainText(`Installed at ${localShim}`);
  await expect(row).not.toContainText("Reinstall to repair");
  expect(existsSync(gemsetShim), "the gemset copy was left to shadow the stable one").toBe(false);
  expect(readFileSync(foreignAya, "utf8")).toBe(foreignScript);
  for (const path of [localShim, homeShim]) {
    const shim = readFileSync(path, "utf8");
    expect(shim).toContain("Generated by Aya");
    expect(shim).toContain(`AYA_CLI='${repoCli}'`);
    expect(shim).not.toContain("app.asar/bin/aya");
  }
});
